config/routes.rb
Rails.application.routes.draw do
  devise_for :users

	root 'media_contents#index'

	resources :media_contents, only: [:create]
	delete 'delete_media', to: 'media_contents#delete_media'
	delete 'delete_all', to: 'media_contents#delete_all'

	resources :profiles, only: [:index]
	post 'vote', to: 'profiles#vote'

	resources :votes, only: [:index]
	resources :chats, only: [:index, :show]
	resources :messages, only: [:create] do
		collection do
			post 'mark_readed'
		end
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
	belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
	belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, :scope => :recipient_id

	scope :involving, -> (user) do
		where("chats.sender_id =? OR chats.recipient_id =?", user.id, user.id)
	end

	scope :between, -> (sender_id,recipient_id) do
		where("(chats.sender_id = ? AND chats.recipient_id = ?) OR (chats.sender_id = ? AND chats.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
	end

end

app/models/likes_photo.rb
class LikesPhoto < ActiveRecord::Base
	belongs_to :media
	belongs_to :media_user, :foreign_key => "media_user_id",
					 :class_name => "User"

	after_create :create_chat

	VOTE_STATUS = {
			'dislike' => 0,
			'like' => 1
	}

	private

	def create_chat
		user_likes_me = LikesPhoto.where(like: VOTE_STATUS['like']).where(user_id: media_user_id).where(media_user_id: user_id).first
    chat_exist = Chat.between(user_id, media_user_id).first

		if user_likes_me && !chat_exist
			Chat.create(
					sender_id: user_id,
					recipient_id:	media_user_id,
			)
		end
	end
end

app/models/media.rb
class Media < ActiveRecord::Base
	mount_uploader :file_name, MediaUploader
	belongs_to :user

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user

	validates_presence_of :body, :chat_id, :user_id

	scope :unreaded, -> (user) do
		where("messages.user_id != ? AND messages.viewed = ?", user.id, false)
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :medias
	has_many :chats, :foreign_key => :sender_id

	has_many :messages
end

app/models/viewed_photo.rb
class ViewedPhoto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
	before_action :authenticate_user!
	before_action :chat_allowed, only: [:show]
	after_action  :mark_readed, only: [:show]

	def index
		@user_chats = Chat.involving(current_user)
	end

	def show
		@chat_id = params[:id]
		@messages = Message.where(chat_id: @chat_id)
	end

	private

	def chat_allowed
		redirect_to root_path unless Chat.involving(current_user).where(id: params[:id])
	end

	def mark_readed
	  @messages.unreaded(current_user).update_all(viewed: true)
	end

end

app/controllers/media_contents_controller.rb
class MediaContentsController < ApplicationController
	before_action :authenticate_user!

	def index
		@media_contents = current_user.medias.all
	end

	def create
		@media = Media.new(file_name: params[:file], user_id: current_user.id)
		if @media.save!
			render json: @media
		else
			render json: { error: 'Failed to process' }, status: 422
		end
	end

	def delete_media
		Media.where(id: params[:media_contents]).destroy_all
		redirect_to root_url
	end

	def delete_all
		current_user.medias.delete_all
		redirect_to root_url
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!
	before_action :chat_allowed, only: [:create]
	#skip_before_filter :verify_authenticity_token
	def create
		@message = current_user.messages.create(messages_params)
	end

	def mark_readed
		begin
			message = Message.where(id: params[:id]).where.not(user_id: current_user.id).first
			message.update_attribute(:viewed, true) if Chat.involving(current_user).where(id: message.chat_id) if message
		end
		render :nothing => true, :status => 200
	end

	private

	def messages_params
		params.require(:message).permit(:body, :chat_id)
	end

	def chat_allowed
		unless Chat.involving(current_user).where(id: params[:chat_id])
		  render text: 'You do not have permission to modify this chat', status: 403
		end
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!
	respond_to :html, :js

	def index
		@photo = get_photo
	end

	def vote
		ViewedPhoto.create(user_id: current_user.id, media_id: params[:media_id], showed_at: DateTime.now)

		begin
			media = Media.find(params[:media_id])
			LikesPhoto.create(
					user_id: current_user.id,
					media_id:	params[:media_id],
					media_user_id: media.user.id,
					like: LikesPhoto::VOTE_STATUS[params[:commit]]
			)

			@chat_id = 0
			chat = Chat.between(current_user.id, media.user.id).first
			if chat && params[:commit] == 'like'
				@chat_id = chat.id
				render status: 302
			else
				@photo_next = get_photo
				render status: 200
			end
		rescue
			render status: 400
		end
	end

	private

	def get_photo
		viewed_photos = ViewedPhoto.where(user_id: current_user.id).where("showed_at >= ?", 6.hours.ago).pluck(:media_id)
		photo = Media.where.not(user_id: current_user.id)
		photo = photo.where('id NOT IN (?)', viewed_photos) unless viewed_photos.blank?
		photo.order("RANDOM()").first
	end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	before_action :authenticate_user!

	def index
		@votes = LikesPhoto.where(user_id: current_user.id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def chat_opponent(chat)
		if chat.recipient == current_user
		  link_to chat.sender.email, chat_path(chat)
		else
			link_to chat.recipient.email, chat_path(chat)
		end
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chats/index.html.erb
<div class="container">
  <div class="row" style="margin-top: 25px;">
    <div class="col-lg-10 col-lg-offset-1">
      <div class="well" >
        <h4><b>All created chats</b></h4>
        <div class="row">
          <div class="col-lg-12">
            <table class="table">
              <% if @user_chats.blank? %>
                No chats found
              <% else %>
                <thead>
                <tr>
                  <th>Email</th>
                  <th>Unreaded messages</th>
                </tr>
                </thead>
                <% @user_chats.each do |chat| %>
                  <tr>
                    <td><%= chat_opponent(chat) %></td>
                    <td><%= chat.messages.unreaded(current_user).count %></td>
                  </tr>
                <% end %>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/chats/show.html.erb
<div class="container">
  <div class="row" style="margin-top: 25px;">
    <div class="col-lg-10 col-lg-offset-1">
      <div class="well" >
        <div class="row">
          <div class="col-lg-12">
            <table class="table table-condensed chat-table">
            <% if @messages.blank? %>
                <span class="no-records">Chat is empty</span>
            <% else %>
              <% @messages.each do |message| %>
                <tr>
                  <td><i><%= message.user.email %></i>: <b><%= message.body %></b></td>
                  <td style="text-align: right;"><%= message.created_at.strftime("%Y-%m-%d %H:%M") %></td>
                </tr>
              <% end %>
            <% end %>
            </table>
            <hr>

            <div class="messages-input-div">
            <%= form_for Message.new, remote: true do |f| %>

              <%= f.hidden_field :chat_id, value: @chat_id %>
              <%= f.text_field :body %>
              <%= f.submit "Send",:class=>'btn btn-primary' %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= subscribe_to "/chat/#{@chat_id}/messages" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tinder</title>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <nav class="navbar navbar-default" role="navigation">
        <div class="container">
          <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="/"><b>My photos</b></a></li>
            <li><a class="navbar-brand" href="/profiles"><b>Find a pair</b></a></li>
            <li><a class="navbar-brand" href="/chats"><b>Chats</b></a></li>
            <li><a class="navbar-brand" href="/votes"><b>Votes history</b></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete, :class =>"navbar-brand right") %></li>


          </ul>
        </div>
      </nav>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/media_contents/index.html.erb
<div class="container">
  <div class="row" style="margin-top: 50px;">
    <div class="col-lg-4 col-lg-offset-1">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Upload new photos</button>
    </div>
  </div>
  <div class="row" style="margin-top: 25px;">
    <div class="col-lg-10 col-lg-offset-1">
      <div class="well">
        <h4><b>All uploaded photos</b></h4><hr>
        <div class="row">
          <div class="col-lg-10">
            <%= form_tag '/delete_media', method: :delete do %>
              <%= submit_tag 'Delete', id: 'delete', class: 'btn btn-danger', disabled: @media_contents.empty? %>
              <br><br>
              <div class="row">
                <div id="media-contents" class="col-lg-12">
                  <% if @media_contents.empty? %>
                    <h5 id="no-media">No photos found</h5>
                  <% else %>
                    <% @media_contents.each do |media| %>
                      <div class="col-lg-4">
                        <div class="thumbnail">
                          <%= image_tag media.file_name.url %>
                          <div class="caption">
                            <p>
                              <%= check_box_tag 'media_contents[]', media.id %>
                            </p>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
          <div class="col-lg-1">
            <%= link_to 'Delete all', delete_all_path, method: :delete, id: 'delete-all', class: 'btn btn-danger', disabled: @media_contents.empty? %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Upload new photo</h4>
      </div>
      <div class="modal-body">
        <%= form_tag '/media_contents', method: :post, class: 'dropzone form', id: 'media-dropzone' do %>
          <div class="fallback">
            <%= file_field_tag 'media', multiple: true %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag 'media_contents.js' %>

app/views/messages/create.js.erb
<% publish_to "/chat/#{@message.chat_id}/messages" do %>
  var row = '<tr>'+
    "<td><i><%= @message.user.email %></i>: <b><%= @message.body %></b></td>"+
    "<td style='text-align: right;'><%= @message.created_at.strftime("%Y-%m-%d %H:%M") %></td>"+
    '</tr>';

  if ($('.no-records').length!=0) {
    $('.no-records').remove();
  }

  $('.chat-table').append(row);
  $("#new_message")[0].reset();


    $.ajax({
      url: '/messages/mark_readed',
      type: 'POST',
      data: { id: <%= @message.id %>}
    });
<% end %>

app/views/profiles/index.html.erb
<div class="container">
  <div class="row" style="margin-top: 25px;">
    <div class="col-lg-10 col-lg-offset-1">
      <div class="well" >
        <h4><b>Vote for photo</b></h4><hr>
        <div class="row">
          <div class="col-lg-12 photo-container">
            <% if @photo.blank? %>
              <h5 id="no-media">No photos found</h5>
            <% else %>
              <%= form_tag("/vote", method: 'post', remote: true ) do %>
                <%= submit_tag 'dislike', class: 'btn btn-danger', style: 'margin-left: 15px; text-transform: uppercase;'  %>
                <%= submit_tag 'like', class: 'btn btn-success', style: 'margin-left: 15px; text-transform: uppercase;'  %>
                <br><br>
                <%= hidden_field_tag 'media_id', @photo.id %>
                <div class="col-lg-4">
                  <div class="thumbnail">
                    <%= image_tag @photo.file_name.url, class: "photo-container" %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/vote.js.erb
switch (<%= response.status %>) {
  case 200:
    $('.photo-container').fadeOut(300, function(){
      <% if @photo_next %>
        $('.photo-container').show();
        $('#media_id').val('<%= @photo_next.id %>');
        $(this).attr('src','<%= @photo_next.file_name.url %>').bind('onreadystatechange load', function(){
          if (this.complete) $(this).fadeIn(300);
        });

      <% else %>
      $('.photo-container').html('<h5 id="no-media">No photos found</h5>');
        $('.photo-container').show();
      <% end %>
    });
    break;
  case 302:
    window.location.replace("<%= chat_path(@chat_id) %>");
    break;
  case 400:
    break;
}

app/views/votes/index.html.erb
<div class="container">
  <div class="row" style="margin-top: 25px;">
    <div class="col-lg-10 col-lg-offset-1">
      <div class="well" >
        <div class="row">
          <div class="col-lg-12">
            <table class="table table-condensed">
              <% if @votes.blank? %>
                No votes found
              <% else %>
                <thead>
                <tr>
                  <th>Photo</th>
                  <th>Email</th>
                  <th>Date</th>
                </tr>
                </thead>
                <% @votes.each do |vote| %>
                  <tr class="<%= vote.like? ? 'success' : 'danger' %>">
                    <td><%= image_tag vote.media.file_name.preview.url  %></td>
                    <td><%= vote.media_user.email %></td>
                    <td><%= vote.created_at.strftime("%Y-%m-%d %H:%M") %></td>
                  </tr>
                <% end %>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>